# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a5368b654b698fc673c0903b08e478991dab3499dd73c0d2535ec53af7fec18bbe634f6262edac3ba5a5c135fd4a6d072b43f3f5bde18e40f46ee6ff8193b44

test:
  secret_key_base: 9e2e4f75ef71109c32fe69b5ae0cc3784d85cfa523c2c52648c2a7f67c162a44a80c133e363a8775f55174147e3306e72f9b661db43feb314029228238064268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
